/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_selectimagedemo_ImageUtil */

#ifndef _Included_com_ytempest_selectimagedemo_ImageUtil
#define _Included_com_ytempest_selectimagedemo_ImageUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_selectimagedemo_ImageUtil
 * Method:    compressBitmap
 * Signature: (Landroid/graphics/Bitmap;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ytempest_selectimagedemo_ImageUtils_compressBitmap
        (JNIEnv *, jclass, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
