/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_videoconvertor_util_VideoUtils */

#ifndef _Included_com_ytempest_audiovideodecode_util_MediaUtils
#define _Included_com_ytempest_audiovideodecode_util_MediaUtils
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_ytempest_audiovideodecode_util_MediaUtils_decodeVideo
        (JNIEnv *, jclass, jstring, jstring);

JNIEXPORT void JNICALL Java_com_ytempest_audiovideodecode_util_MediaUtils_decodeAudio
        (JNIEnv *, jclass, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
