/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_opensldemo_util_AudioPlayer */

#ifndef _Included_com_ytempest_opensldemo_util_AudioPlayer
#define _Included_com_ytempest_opensldemo_util_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_opensldemo_util_AudioPlayer
 * Method:    play
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_opensldemo_util_AudioPlayer_play
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
