/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_vectorconvertor_util_EffectUtils */

#ifndef _Included_com_ytempest_vectorconvertor_util_EffectUtils
#define _Included_com_ytempest_vectorconvertor_util_EffectUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_ytempest_vectorconvertor_util_EffectUtils_MODE_NORMAL
#define com_ytempest_vectorconvertor_util_EffectUtils_MODE_NORMAL 1L
/*
 * Class:     com_ytempest_vectorconvertor_util_EffectUtils
 * Method:    convert
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_voiceconvertor_util_EffectUtils_convert
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
