/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_andfixdemo_fix_HandlerNative */

#ifndef _Included_com_ytempest_andfixdemo_fix_HandlerNative
#define _Included_com_ytempest_andfixdemo_fix_HandlerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_andfixdemo_fix_HandlerNative
 * Method:    replaceMethod
 * Signature: (Ljava/lang/reflect/Method;Ljava/lang/reflect/Method;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_andfixdemo_andfix_HandlerNative_replaceMethod
        (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_ytempest_andfixdemo_fix_HandlerNative
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_andfixdemo_andfix_HandlerNative_init
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
