/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_ytempest_ndkdemo_util_DiffUtils */

#ifndef _Included_com_ytempest_ndkdemo_util_DiffUtils
#define _Included_com_ytempest_ndkdemo_util_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_ndkdemo_util_DiffUtils
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_ndkdemo_util_DiffUtils_diff
        (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     com_ytempest_ndkdemo_util_DiffUtils
 * Method:    merge
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_ndkdemo_util_DiffUtils_merge
        (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
