/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_ndkdemo_util_EncryptUtils */

#ifndef _Included_com_ytempest_ndkdemo_util_EncryptUtils
#define _Included_com_ytempest_ndkdemo_util_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_ndkdemo_util_EncryptUtils
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_ndkdemo_util_EncryptUtils_encrypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_ytempest_ndkdemo_util_EncryptUtils
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_ndkdemo_util_EncryptUtils_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
