/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ytempest_mediaplayer_MediaPlayer */

#ifndef _Included_com_ytempest_mediaplayer_MediaPlayer
#define _Included_com_ytempest_mediaplayer_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ytempest_mediaplayer_MediaPlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_mediaplayer_MediaPlayer_playVideo
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_ytempest_mediaplayer_MediaPlayer
 * Method:    playAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ytempest_mediaplayer_MediaPlayer_playAudio
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
